# Nolan Kiel
## Week 11 - 03/29/2022
### Python Numpy Intro

In [1]:
import numpy as np

In [3]:
np.__version__

'1.18.5'

In [4]:
arr = np.array([1,2,3,4,5,6])

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr3[1,0:2,1:3]

In [9]:
# different data elements dims
arr = np.array([  [[1,2], [4,5]], [[7,8],[8,11]] ])
arr

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [ 8, 11]]])

In [10]:
arr.ndim

3

In [11]:
arr.shape

(2, 2, 2)

In [12]:
arr = np.array([  [[1,2], [4,5]], [[7,8],[8,11,3]] ])
arr

array([[list([1, 2]), list([4, 5])],
       [list([7, 8]), list([8, 11, 3])]], dtype=object)

In [13]:
arr = np.array([  [[1,2], [4,5]], [[7,8],[8,11,5]] ])
arr

array([[list([1, 2]), list([4, 5])],
       [list([7, 8]), list([8, 11, 5])]], dtype=object)

In [14]:
arr = np.array([  [[1,2], [4,5]], [[7,8],[8,11,3]] ])
arr

array([[list([1, 2]), list([4, 5])],
       [list([7, 8]), list([8, 11, 3])]], dtype=object)

In [15]:
arr.ndim

2

In [16]:
arr.shape

(2, 2)

In [17]:
arr[0]

array([list([1, 2]), list([4, 5])], dtype=object)

In [18]:
arr[1]

array([list([7, 8]), list([8, 11, 3])], dtype=object)

In [19]:
arr[1,1]

[8, 11, 3]

In [20]:
arr[0,1]

[4, 5]

In [21]:
arr[0,1][-1]

5

In [23]:
arr[1,0]

[7, 8]