# Nolan Kiel
## Week 12 - 03/7/2022
### Python Numpy Universal Functions

In [1]:
import numpy as np

arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
#sqrt 

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [3]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
#randn
arr1 = np.random.randn(10) # return a sample from the "standart normal" distribution
arr1

array([ 0.47038072,  0.27183034, -1.20610983,  0.15768446,  1.18231513,
       -0.35047076,  0.44326203, -1.47420034,  0.41033925, -0.50087839])

In [6]:
arr2 = np.random.randn(10)
arr2

array([ 0.75899231, -0.77514642, -1.40039792, -0.98028775,  0.10029925,
       -0.63487196, -0.14417751,  0.15363001,  1.80716931, -0.92997828])

In [7]:
#add
np.add(arr1,arr2)

array([ 1.22937303, -0.50331608, -2.60650775, -0.82260329,  1.28261438,
       -0.98534271,  0.29908453, -1.32057034,  2.21750856, -1.43085667])

In [8]:
# maximum
np.maximum(arr1,arr2)

array([ 0.75899231,  0.27183034, -1.20610983,  0.15768446,  1.18231513,
       -0.35047076,  0.44326203,  0.15363001,  1.80716931, -0.50087839])

In [10]:
arr1 = np.ones(9).reshape((3,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
#array filtering
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [14]:
# replace values of an array, using where
np.where(arr<4, True, False)

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [15]:
#np.where(array cond,x,y) Return elements chosen from 'x' or 'y' depending on 'condition'
np.where(arr<4,-1,-2)


array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [16]:
np.where((arr<4)&(arr>2),-1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [17]:
#where with 1-D
arr1 = np.array([1,2,3,4,5])
arr2 = arr1*10
arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]


In [18]:
zip(arr1,arr2,arr_b)


In [19]:
list(zip(arr1,arr2,arr_b))

[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]

In [20]:
arr3 = [r1 if b else r2 for r1,r2,b in zip(arr1,arr2,arr_b)]
arr3

[1, 20, 3, 4, 50]

In [21]:
# using np.where
arr3 = np.where(arr_b, arr1, arr2)
arr3

array([ 1, 20,  3,  4, 50])

In [24]:
# using where with 2-D array
arr1 = np.array([[1,2],[3,4]])
arr1 = np.array([[5,6],[7,8]])
arr1 = np.array([[True,False],[True,True]])

print("arr1: ", arr1, end ="\n\n")
print("arr2: ", arr2, end ="\n\n")
print("cond: ", cond, end ="\n\n")

arr1:  [[ True False]
 [ True  True]]

arr2:  [10 20 30 40 50]



NameError: name 'cond' is not defined

In [25]:
np.where(cond,arr1,arr2)

NameError: name 'cond' is not defined

In [26]:
np.where([[True,False],[True,True]], [[5,6],[7,8]], [[1,2],[3,4]])

array([[5, 2],
       [7, 8]])

In [29]:
# a short use of randn
from numpy.random import rand
arr = randn(3,3)
arr

SyntaxError: invalid syntax (<ipython-input-29-30700f4f6c18>, line 3)

In [30]:
#boolean arrays
# any
arr_b = np.array([True,False,True,False,False])
arr_b.any()#return true is any of the elements of 'a' evaluate to true.


True

In [31]:
arr_b.all()# returns true if all elements evaluate to true


False

In [32]:
# Unique()
#find the unique elements of an array
fruits = np.array(['Apple','cherry','Orange','Cherry','Banana'])
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange', 'cherry'], dtype='<U6')

In [33]:
np.in1d(['Apple','cherry','Grape'],fruits)

array([ True,  True, False])

In [1]:
import numpy as np

In [2]:
# descriptive statistical measures
arr = np.array([ [1,2,3], [4,5,6], [7,8,9]  ])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr.sum()

45

In [4]:
arr.sum(0)

array([12, 15, 18])

In [5]:
arr.sum(1)

array([ 6, 15, 24])

In [6]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [8]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [9]:
np.sum(arr, axis=None)

45

In [10]:
#mean()
arr.mean()

5.0

In [11]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
arr.mean(0)

array([4., 5., 6.])

In [13]:
arr.mean(1)

array([2., 5., 8.])

In [16]:
np.mean(arr, axis=0)

array([4., 5., 6.])

In [17]:
np.mean(arr, axis=None)

5.0

In [18]:
arr.var()

6.666666666666667

In [19]:
arr.var(1)

array([0.66666667, 0.66666667, 0.66666667])

In [20]:
arr.std()

2.581988897471611

In [21]:
arr = np.array([3,6,8,1,9,10,3,5,63,9,12,10,15,11,14])

arr.sort()


In [22]:
arr

array([ 1,  3,  3,  5,  6,  8,  9,  9, 10, 10, 11, 12, 14, 15, 63])

In [23]:
#Trasnspose
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr.shape)
print(arr)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [24]:
t = arr.T
t

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [25]:
t.shape

(4, 2)

In [26]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [27]:
arr.transpose().shape

(4, 2)

In [28]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [30]:
arr.shape

(2, 4)

In [31]:
arr.transpose((0,1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [34]:
arr.shape

(2, 4)

In [35]:
arr.transpose((0,1)).shape

(2, 4)

In [36]:
arr.transpose((1,0)).shape

(4, 2)

In [38]:
arr_3d = np.arange(20).reshape((2,5,2))
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [39]:
arr_3d.transpose((0,1,2)) #no change in the axis, some order

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [40]:
arr_3d.transpose((0,1,2)).shape

(2, 5, 2)

In [41]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [42]:
arr_3d.transpose((1,0,2)).shape

(5, 2, 2)

In [43]:
arr_3d.T

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [45]:
# random
np.random.random((4,4)) #Returns numbers in this interval [0.0, 1.0)

array([[0.90035599, 0.47388616, 0.43118949, 0.5614471 ],
       [0.66616754, 0.34971532, 0.55418722, 0.58461694],
       [0.23688117, 0.27208031, 0.53761291, 0.30351446],
       [0.42069813, 0.24166218, 0.61333546, 0.72511001]])

In [46]:
from numpy.random import random 

random((4,4))

array([[0.11153101, 0.39127001, 0.58980237, 0.49967283],
       [0.65070937, 0.34099496, 0.57331018, 0.93237778],
       [0.11190938, 0.1725401 , 0.7959912 , 0.72237356],
       [0.92830816, 0.03213885, 0.4085829 , 0.62725253]])

In [47]:
from numpy.random import randn
randn(5,5)


array([[-0.80669273,  0.50164835,  0.30751115, -0.15463494, -0.22402475],
       [-0.34439114,  0.92668636, -0.17280238,  1.25053246,  0.52612886],
       [ 0.80109132,  1.15771058, -0.58165949,  1.9413616 ,  1.52012988],
       [ 0.66052853, -0.74155513, -0.17264521,  0.30928974,  1.93320381],
       [-1.5157031 ,  2.34084877,  0.58646639, -0.65822964,  1.40975462]])

In [48]:
randn(5)

array([-0.38283762, -0.55664859,  0.2344517 ,  0.54575335, -0.99839825])

In [49]:
np.random.randint(10,50)

38

In [50]:
# Joining NumPy Arrays
# 1-d array

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1, "\n", arr2)


[1 2 3 4 5] 
 [ 6  7  8  9 10]


In [51]:
arr = np.concatenate((arr1,arr2))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr.shape

(10,)

In [54]:
# 2-d arrays
arr1 = np.array([ [1,2], [3,4]])
arr2 = np.array([ [5,6], [7,8]])
print(arr1, "\n", arr2)

[[1 2]
 [3 4]] 
 [[5 6]
 [7 8]]


In [56]:
arr = np.concatenate((arr1,arr2))
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [57]:
arr1.shape

(2, 2)

In [59]:
arr.shape

(4, 2)

In [60]:
arr = np.concatenate((arr1,arr2), axis=1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [61]:
arr.shape

(2, 4)

In [62]:
arr = np.concatenate((arr1,arr2), axis=0)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [63]:
#Splitting numpy arrays
arr = np.array([1,2,3,4,5,6,])
arr_s = np.array_split(arr,3)
arr_s

[array([1, 2]), array([3, 4]), array([5, 6])]

In [64]:
arr_s[0]

array([1, 2])

In [65]:
arr_s[2]

array([5, 6])

In [ ]:
website = "http://docs.scipy.org/doc/numpy/reference/"

""""