# Nolan Kiel
## Week 11 - 03/31/2022
### Python Numpy - Processing Arrays

In [1]:
import numpy as np

In [2]:
lst = [11,22,33,44,55,66,77]
lst

[11, 22, 33, 44, 55, 66, 77]

In [3]:
arr = np.array(lst)
arr

array([11, 22, 33, 44, 55, 66, 77])

In [4]:
arr.dtype

dtype('int32')

In [6]:
lst2 = [1.3,4.5,6.8,9.0]
arr2 = np.array(lst2)
arr2

array([1.3, 4.5, 6.8, 9. ])

In [7]:
arr2.dtype

dtype('float64')

In [8]:
fruits = ["Orange", "Apple", "Cherry", "Grape"]

my_strArr = np.array(fruits)
my_strArr

array(['Orange', 'Apple', 'Cherry', 'Grape'], dtype='<U6')

In [9]:
my_strArr.dtype

dtype('<U6')

In [13]:
d = ['Orange', "Apple", "Cherry", "Grape",1,2,3,4,5 [6,7,8,9,10]]
arr_df = np.array(d)
arr_df

TypeError: 'int' object is not subscriptable

In [11]:
my_arr2 = np.array([11,22,33,44,55], dtype='S')

In [14]:
my_arr2.dtype

dtype('S2')

In [17]:
my_arr3 = np.array([1,2,3,4,5,6],  dtype='i4')
my_arr3

array([1, 2, 3, 4, 5, 6])

In [18]:
my_arr3 = np.array([1,2,3,4,5,6],  dtype='i8')
my_arr3

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [20]:
my_arr3.dtype

dtype('int64')

In [21]:
# cnverting data type on existig arrays
# using astype
scores = [99.9,98.7,89.5,78.9,100.0,88.99]
arr_sc = np.array(scores)
arr_sc

array([ 99.9 ,  98.7 ,  89.5 ,  78.9 , 100.  ,  88.99])

In [22]:
arr_sc.dtype

dtype('float64')

In [23]:
arr = arr_sc.astype('i')
arr

array([ 99,  98,  89,  78, 100,  88], dtype=int32)

In [24]:
arr = np.array([1,0,0,1,4,5,6,7,9,1,0])
arr

array([1, 0, 0, 1, 4, 5, 6, 7, 9, 1, 0])

In [25]:
arr.dtype

dtype('int32')

In [26]:
arr_bool = arr.astype('bool')

In [28]:
print(arr)
print(arr_bool)

[1 0 0 1 4 5 6 7 9 1 0]
[ True False False  True  True  True  True  True  True  True False]


In [33]:
# numpy array copy vs view
# creating an array from a nested list
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]
my_list = [lst1,lst2]
my_list

[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]

In [34]:
print(my_list)

[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]


In [35]:
arr = np.array(my_list)


In [36]:
arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [37]:
arr.ndim

2

In [40]:
#copy and view, instead of using = 
c_arr = arr.copy()
c_arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [41]:
c_arr[1,3] = 40

In [42]:
c_arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 40, 55]])

In [43]:
arr_v = arr.view()
arr_v

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [44]:
arr[0,0] = 15

In [45]:
arr

array([[15,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [46]:
arr_v

array([[15,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [47]:
#numPy array Shape
arr

array([[15,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [48]:
arr.shape

(2, 5)

In [49]:
arr = np.array([1,2,3,4,5,6], ndmin=5)
arr

array([[[[[1, 2, 3, 4, 5, 6]]]]])

In [50]:
arr.ndim

5

In [51]:
arr.shape

(1, 1, 1, 1, 6)

In [52]:
a = np.array([[2,3,4,5],[6,7,8,9]])
print(np.shape(a))

(2, 4)


In [53]:
a.shape[0]

2

In [54]:
a.shape[1]

4

In [55]:
#Stacking
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
             [7,8]])

In [56]:
v = np.vstack((a,b))
v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [57]:
v.shape

(4, 2)

In [58]:
h = np.hstack((a,b))
h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [59]:
h.shape

(2, 4)

In [60]:
# creating array from file
f = open("Data.txt","w")
f.write("1, 2, 3\n")
f.write("4, 5, 6")
f.close
f = open("Data.txt", "r")
print(f.read())

1, 2, 3
4, 5, 6


In [61]:
arr = np.genfromtxt("data.txt", dtype=None, encoding=None, delimiter=",")
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
arr.dtype

dtype('int32')

In [65]:
file_data = np.loadtxt("Data1.txt",dtype=int)

ValueError: could not convert string to float: '1,'